---
- name: Ansible playbook for installing the flutter
  hosts: localhost
  vars:
    is_WSL: "{{ ansible_kernel.find('WSL') }}"
  tasks:
    - name: Check flutter resources
      ansible.builtin.stat:
        path: ./sources/bin/flutter
      register: p
    - name: Get Flutter sources
      when: not p.stat.exists
      ansible.builtin.git:
        repo: https://github.com/flutter/flutter.git
        dest: ./sources
        version: stable

    - name: Download flutter precache
      command: ./sources/bin/flutter precache
    - name: Disable flutter analytics
      command: ./sources/bin/flutter config --no-analytics
    - name: Download flutter precache
      command: ./sources/bin/dart --disable-analytics
    - name: Enable Flutter for linux
      command: ./sources/bin/flutter config --enable-linux-desktop

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ is_WSL }}"

    - name: Check vnc folder
      ansible.builtin.stat:
        path: ~/.vnc/
      register: vnc
    - name: Create the folder if not exists
      when: not vnc.stat.exists
      ansible.builtin.file:
        path: ~/.vnc/
        state: directory
        mode: 0777

    - name: Set vncserver config
      when: is_WSL != "-1"
      ansible.builtin.copy:
        dest: ~/.vnc/tightvncserver.conf
        content: |
          geometry = "800x480";
          depth = 24;
          SecurityTypes = "None";
          localhost = "yes";

    - name: Enable and star vncserver in case of WSL
      when: is_WSL != "-1"
      command: tigervncserver -useold -noxstartup -SecurityTypes None -localhost yes :1