---
- name: Ansible playbook for installing the flutter
  hosts: localhost
  tasks:
    - name: Check flutter resources
      ansible.builtin.stat:
        path: /opt/flutter/bin
      register: p
    - name: Get Flutter sources
      when: not p.stat.exists
      ansible.builtin.git:
        repo: https://github.com/flutter/flutter.git
        dest: /opt/flutter
        version: stable

    - name: Download flutter precache
      command: /opt/flutter/bin/flutter precache
    - name: Disable flutter analytics
      command: /opt/flutter/bin/flutter config --no-analytics
    - name: Download flutter precache
      command: /opt/flutter/bin/dart --disable-analytics
    - name: Enable Flutter for linux
      command: flutter config --enable-linux-desktop


